### ISSUE TITLE
Lobster creates too many jobs and shows none waiting

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#158]
See title.  Leaves me with:
```
2015-07-28 05:38:11,831 [ INFO] - ...er-1.2-py2.7.egg/lobster/cmssw/job.py  433: creating job(s) 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708
2015-07-28 05:38:13,152 [ INFO] - ...er-1.2-py2.7.egg/lobster/cmssw/job.py  433: creating job(s) 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758
2015-07-28 05:38:14,304 [ INFO] - ...er-1.2-py2.7.egg/lobster/cmssw/job.py  433: creating job(s) 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778
2015-07-28 05:43:15,480 [ INFO] - ...Lobster-1.2-py2.7.egg/lobster/core.py  220: 0 out of 0 workers busy; 0 jobs running, 0 waiting; 104677 jobits left
2015-07-28 05:48:15,491 [ INFO] - ...Lobster-1.2-py2.7.egg/lobster/core.py  220: 1 out of 1 workers busy; 0 jobs running, 0 waiting; 104677 jobits left
```

And:
```
crcfe01: work_queue_status
PROJECT            HOST                   PORT WAITING RUNNING COMPLETE WORKERS
lobster_mc_example earth.crc.nd.edu       9000       0       1      139       1
lobster_single     earth.crc.nd.edu       9001    1778       0        0       1
…
```
the latter being my master.  Work queue version:
```
2015-07-28 05:17:22,112 [ INFO] - ...Lobster-1.2-py2.7.egg/lobster/core.py  126: using wq from /afs/crc.nd.edu/group/ccl/software/cctools-011-b8c084f8-cvmfs-40cf5bba/x86_64/redhat6/lib/python2.6/site-packages/work_queue.py
```

**Comment by annawoodard** [comment]
The problem with tasks waiting is on the cctools side and has been reported on slack. @btovar, should we make a cctools issue?

**Comment by matz-e** [comment]
D'oh!  Thanks!  I guess we should close this, then?  Or maybe once it's fixed in cctools?

**Comment by annawoodard** [comment]
Yeah, let's keep it.

**Comment by btovar** [comment]
I deployed  012-94739ca8-cvmfs-40cf5bba with a fix. Could you confirm it works for you?

**Comment by annawoodard** [comment]
on it

**Comment by annawoodard** [comment]
I am still seeing 0 waiting. @matz-e, could this be on our side, after all?

**Comment by matz-e** [comment]
I'll have a look into that later.

**Comment by annawoodard** [comment]
In my second test, the number waiting seems to be normal. Maybe it's just taking slightly longer to update than we're used to? I'll keep an eye on it through a few more tests and see if I spot any patterns.

**Comment by btovar** [comment]
There was a bug on the master side. q.stats_hierarchy did not show tasks waiting at the master, only those waiting at foreman and workers. Tasks waiting at a foreman/worker are reported to their respective master every three minutes.

**Comment by annawoodard** [comment]
Thanks, @btovar! I'll wait on @matz-e to confirm, but I think we can close this issue.

**Comment by btovar** [comment]
What does q.stat says? (No stats_hierarchy).

**Comment by matz-e** [comment]
@annawoodard I see jobs waiting again.  Closing this issue.  Thanks for the fix, @btovar!
